Greeting.create(greeting: "Hello, World! in English")
Greeting.create(greeting: "Ciao, Mondo! in Italian")
Greeting.create(greeting: "Hola, Mundo! in Spanish")
Greeting.create(greeting: "Hallo, Welt! in German")
Greeting.create(greeting: "Bonjour, Monde! in French")
Greeting.create(greeting: "こんにちは、世界! in Japanese")
Greeting.create(greeting: "你好，世界! in Chinese")
Greeting.create(greeting: "مرحبا بك في العالم! in Arabic")
Greeting.create(greeting: "Salamu, Dunia! in Swahili")
Greeting.create(greeting: "Mbote, Mokili! in Lingala")
Greeting.create(greeting: "Molo, Iihlabathi! in Xhosa")
Greeting.create(greeting: "Ndewo, Uwa! in Igbo")         
Greeting.create(greeting: "Akwaaba, Wiase! in Twi")
